//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Application> Applications { get; set; }
        public DbSet<Buyer> Buyers { get; set; }
        public DbSet<BuyTicket> BuyTickets { get; set; }
        public DbSet<Chair> Chairs { get; set; }
        public DbSet<Concert> Concerts { get; set; }
        public DbSet<ConcertPrice> ConcertPrices { get; set; }
        public DbSet<ExceptionHandler> ExceptionHandlers { get; set; }
        public DbSet<Hall> Halls { get; set; }
        public DbSet<HallPart> HallParts { get; set; }
        public DbSet<PriceStyle> PriceStyles { get; set; }
        public DbSet<Profile> Profiles { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<ShowTime> ShowTimes { get; set; }
        public DbSet<Singer> Singers { get; set; }
        public DbSet<TicketStatu> TicketStatus { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Ticket> Tickets { get; set; }
        public DbSet<NoSelection> NoSelections { get; set; }
        public DbSet<Advertise> Advertises { get; set; }
        public DbSet<Payment> Payments { get; set; }
        public DbSet<ConcertShowTime> ConcertShowTimes { get; set; }
        public DbSet<ConcertTicket> ConcertTickets { get; set; }
    }
}
